### ISSUE TITLE
Running JupyterLab alongside the Cylc UI

### ISSUE THREAD

**Issue by dpmatthews** [cylc/cylc-uiserver#298]
This is possible now that the uiserver is a jupyter server extension (#230).
We should:
* document how to do this
  * https://github.com/cylc/cylc-doc/issues/628
* explain how to choose whether you start with JupyterLab or the Cylc UI on launch
  * https://github.com/cylc/cylc-doc/issues/628
* investigate how to support switching between the 2 applications (e.g. adding a link in the Cylc UI)
  * #470
* investigate implications for multi-user support
  * https://github.com/cylc/cylc-doc/pull/625

**Comment by jbaksta** [comment]
To get started with this, I suppose we did a couple things here at NCAR to facilitate accessing the Cylc-UI through our current JupyterHub deployment.

- The first one was to get the Cylc Extension registered with Jupyter server. This wasn't complicated, dropped a file in `$PREFIX/etc/jupyter/jupyter_server_config.d`. 
- The next was to create a basic front-end extension to JupyterLab for easy navigation to the Cylc-UI.

<img width="218" alt="image" src="https://user-images.githubusercontent.com/2792834/156080928-0d22fda9-073c-47d9-b4c2-42ae6161f52f.png">

One thing that I noticed on the setup that I'll have to address at our site is the hub button in the Cylc UI doesn't reference the hub when behind a reverse proxy. I'm sure I'll tweak that in the near future, but but nevertheless, it's there.

I'm also not sure about the issue regarding multiple users, but most of our users will not access other users Cylc workflows.

I think my next thing will be to put the Cyl-UI inside of a JupyterLab Launcher Tab instead of a whole new window. Many of our users will want to watch the GUI while editing their flows in the same space. This would allow such workflow.

**Comment by oliver-sanders** [comment]
I've created a dedicated issue for the switching of Jupyter Server extensions (e.g. switching between Jupyter Lab and Cylc UI Server) - #470

Jupyter Server can list extensions and extract the root endpoint from them, however, this might be a bit clunky (can't remember) so it might be worth pushing something upstream as these toggles need to be implemented in every server extension separately.

**Comment by oliver-sanders** [comment]
The multi-user support side of things is now covered by  - https://github.com/cylc/cylc-doc/pull/625

**Comment by oliver-sanders** [comment]
Also opened an issue covering the sharing of context between server extensions - #472

**Comment by oliver-sanders** [comment]
The topics on this issue should now all be covered by specific ones so I'll close this umbrella issue.

If anyone comes across this issue and has more to suggest, feel free reach out to us on Discourse or our developer chat on Element (links in the [README](https://github.com/cylc/cylc-flow#readme)).

We're open to contributions if you have any code you'd like to share.
