### ISSUE TITLE
Add extra options to task left click menu

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-uiserver#552]
### Problem

Problem is too strong a word. I'm finding, when I have a task expanded, showing the numbered tasks, I bring up the numbered item if I want to do something like `Kill` the task. 

![image](https://github.com/cylc/cylc-uiserver/assets/15375218/ffa4b483-1dfa-46fa-8b2a-b5974f177e81)

### Proposed Solution

Add some extra options so they are in both the top level task menu and the individual task menu, where it makes sense. For example, `Kill` and `Poll`. `Logs` already appears in both menu's so this would (I imagine) be a small extension?

**Comment by hjoliver** [comment]
FYI, the "numbered tasks" are "jobs".  As in,  a task can submit multiple jobs.

I presume your yellow highlighter has changed running job #5 (blue) to green (which is supposed to represent a succeeded job). 

To explain the status quo, when you want to poll or kill a job, you really target a specific **task** instance (`<cycle>/<name>`) and the scheduler does it if the task currently has an active job. 
 
That said, I think it's a reasonable suggestion to add `poll`, and `kill` to the menu for running jobs, but note that it will only ever affect menu for the latest job, and only while it is still running.  And there aren't any other commands that target jobs rather than tasks.

**Comment by ColemanTom** [comment]
Sorry about the terminology and my lazyness not changing from highlight to a pen to circle it like I had originally thought to do. Yes, it was a running job.

And yes, I only thought for the latest active job as you describe. Thanks for clarifying what I meant.

**Comment by oliver-sanders** [comment]
Hi, I'm not sure what commands you're expecting to see in which menu.

* There are some commands which are applicable to tasks but not jobs (e.g. set-outputs). These will *not* be added to the job menu.
* There are some tasks commands which may be applicable to jobs but don't appear in the job menu at present for technical reasons.

**Comment by hjoliver** [comment]
> Hi, I'm not sure what commands you're expecting to see in which menu.

See my comment above - I said it could only be poll and kill, and only for the latest job and only while it active - and @ColemanTom agreed.

**Comment by oliver-sanders** [comment]
Currently we don't have the ability to poll or kill a specific job as these commands are issued against the task.

When this cylc-flow issue is solved, the poll and kill mutations will automatically show up in the job menu in the GUI (it's auto generated): https://github.com/cylc/cylc-flow/issues/5950

Closing this as transferred to https://github.com/cylc/cylc-flow/issues/5950
