### ISSUE TITLE
Attempt to avoid printing stack traces for missing workflows to JH logs

### ISSUE THREAD

**Issue by jarich** [cylc/cylc-uiserver#564]
### Problem

Some of my users have a lot of workflows in unstable states, as can occur frequently when people are just getting started. Workflows that start to run, but hit submit-failed on their first job, or workflows that weren't cleaned up with `cylc clean` and probably a host of other reasons.

This means that when those uses attempt to use the Cylc hub to view their workflows, the logs are filled with stack traces explaining that Cylc `Cannot determine whether workflow is running on <hostname>`:

![image](https://github.com/cylc/cylc-uiserver/assets/13433/c5675cc5-9de8-42e1-833a-fc8040fc1c68)

In addition to being very spammy and filling the logs (my logs are easily 90% these backtraces), these seem to slow down the viewing of workflows that Cylc can confirm are running. Users cannot see the cylc hub logs, so they don't know they need to clean things up.

### Proposed Solution

The Cylc UI Servers don't spit out backtraces if they can detect that the UI Server is running through the hub. I don't know if this is feasible, but I'd rather just see:

```
[E 2024-03-14 22:52:42.144 CylcUIServer] Cannot determine whether workflow <workflow> is running on <host>.
```

without the backtrace. I'd be happy to set something in `jupyter_config.py` to achieve this.

An alternate (or parallel) solution might have the Cylc UI Servers keep a count of how many times they have been unable to determine whether a workflow is running, and after X failed attempts stop attempting to interact with those workflows for a little while, in the same was as platform hosts are deprioritised after some number of unsuccessful attempts.

**Comment by oliver-sanders** [comment]
> Cannot determine whether workflow is running on <hostname>

To explain this error:
* Cylc looks for running workflows by finding `contact` files in the cylc-run directory.
* When it finds a contact file, it attempts to ping the workflow to check if it is still running.
* If the ping fails (i.e. it fails to connect to the workflow), then it will `ssh` to the host to check if the process is still running.
* If it fails to SSH to the host or cannot run the `cylc psutil` command on the host (used to check the process), then the error you are reporting will be raised.

We could filter these messages out, but there are other consequences besides logging. Under normal circumstances, we would not expect to see this message. This message may suggest a site setup problem (e.g. cannot SSH to host or cannot run the Cylc command on the host).

Best guesses at debugging:

* Can the host where the UI Server is running access the configured port range?
* Can the host where the UI Server is running SSH to the host(s) where the workflows run?
* Does the `cylc psutil` command work on the host(s) where the workflows run?

Here's an example `psutil` command which retrieves the load average and virtual memory for the host it is run on:

```
$ cylc psutil <<< '[["getloadavg"], ["virtual_memory"]]'
```

> The Cylc UI Servers don't spit out backtraces if they can detect that the UI Server is running through the hub

The tracebacks should be logged for all configurations, but they might not go to stderr depending on setup. Cylc UI Servers log to the `~/.cylc/uiserver/log/log` file. If you run the `cylc gui` command or the `cylc hub` command (with `LocalProcessSpawner` configured), these log messages will also go to stderr. For other configurations of `cylc hub`, stderr will not point back at the terminal you used to run the command.

**Comment by oliver-sanders** [comment]
The error is either coming from here:

https://github.com/cylc/cylc-flow/blob/fafcdcffa7ff97d28053c6606e5905f67677f6a6/cylc/flow/workflow_files.py#L399-L405

(meaning that the `cylc psutil` command did not return within 10 seconds)

Or here:

https://github.com/cylc/cylc-flow/blob/fafcdcffa7ff97d28053c6606e5905f67677f6a6/cylc/flow/workflow_files.py#L427-L431

(meaning that the `cylc psutil` command errored).

You might want to run the `cylc gui` in debug mode to squeeze out a little more logging to help debug.

**Comment by hjoliver** [comment]
@jarich - yeah that's not just a spurious error, it literally indicates that Cylc can't connect to the scheduler to confirm that a workflow really is running an existing contact file says it is running. In that situation we can't get information about the workflow and we can't safely conclude that its not running and remove the orphaned contact file.

So I think you need to figure out (with reference to @oliver-sanders response above) why you are seeing that. Are your UI Servers running on hosts that can't connect to the scheduler hosts?

The only times I see this error locally (via CLI or web UI) is:
- temporary network outages, so that Cylc can't connect to the workflow hosts
- after running workflows on "localhost" inside interactive Slurm sessions (where Slurm provides temporary interactive access to a compute node, via JupyterHub). Once the session ends the Cylc scheduler gets hard-killed by Slurm, leaving its contact file behind on the shared FS. When the user next does a `cylc scan` the contact file still exists, but the system blocks connections to the (former) scheduler host node because the user no longer has any running processes there.

**Comment by oliver-sanders** [comment]
Closing this issue for now as I don't think there's anything to do UIS side. Still happy help with debugging though, drop us a line.
