### ISSUE TITLE
request for changes to graph data json schema

### ISSUE THREAD

**Issue by MartinRyan** [cylc/cylc-uiserver#77]
To allow the graph to function correctly certain data properties are required, here is an example json schema. Edge source and target are node ids. Parent is a node id, this allows the parent node to collapse child nodes. Runpercent is to allow display of runtime on a running node. 
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "nodes": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "data": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                },
                "parent": {
                  "type": "string"
                },
                "label": {
                  "type": "string"
                },
                "state": {
                  "type": "string"
                },
                "runpercent": {
                  "type": "integer"
                }
              },
              "required": [
                "id",
                "parent",
                "label",
                "state",
                "runpercent"
              ]
            }
          },
          "required": [
            "data"
          ]
        }
      ]
    },
    "edges": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "data": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                },
                "source": {
                  "type": "string"
                },
                "target": {
                  "type": "string"
                },
                "label": {
                  "type": "string"
                }
              },
              "required": [
                "id",
                "source",
                "target",
                "label"
              ]
            }
          },
          "required": [
            "data"
          ]
        }
      ]
    }
  },
  "required": [
    "nodes",
    "edges"
  ]
}
```
an example of the json output
```
{
    "nodes": [{
            "data": {
                "id": "338c432b-9f96-420c-908f-84d06539cb1d",
                "parent": "0696f731-4522-4f01-9bf1-b5d035a117a2",
                "label": "long_start_12.20150219T1200Z",
                "state": "succeeded",
                "runpercent": 0
            }
        }
    ],
    "edges": [{
        "data": {
            "id": "1095",
            "source": "338c432b-9f96-420c-908f-84d06539cb1d",
            "target": "946be865-95c9-4cf1-89f5-a06400f739b9",
            "label": "ensemble_thunderbirds_are_go_forecast_002.20150219T1200Z (interaction) ensemble_sync_happy.20150219T1200Z"
        }
    }]
}
```

**Comment by hjoliver** [comment]
Run-percent needs to be computed client-side, from start-time, current-time, and expected or average run-length.  We discussed this somewhere recently, but offhand I can't recall exactly where. Basically it's a simple calculation that could be done at either end, but if server-side it would require constant frequent updates over the network which seem unnecessary.

Hopefully changes to the radial progress bars on nodes representing running jobs can be updated every so often without redoing the graph layout. Initially it could just be done whenever the graph updates though.

**Comment by hjoliver** [comment]
Aside from run-percent, I think everything you need is already available, just not in exactly the form you want for the graph view.  I expect what you're asking for will be clearer to @dwsutherland, but as a general rule we need to be avoid view-specific queries that result in duplicating data unnecessarily (for large-workflow efficiency reasons; we always expected that the common data would require some client-side massaging, differently for each view).

**Comment by dwsutherland** [comment]
Given a workflow:
```
[cylc]
    cycle point format = CCYYMMDDThh
    UTC mode = True
[scheduling]
    initial cycle point = 20190101T00
    max active cycle points = 2
    [[graph]]
        P1D = """
foo[-P1D] => foo
foo => baa => bar => baz  # long chain
qux  # isolate
"""
[runtime]
    [[root]]
        script = sleep 15; echo "$CYLC_TASK_NAME"
    [[FAM]]
    [[baa, bar, baz]]
        inherit = FAM
    [[qux]]
        script = sleep 60; echo "$CYLC_TASK_NAME"
```
The following query;
```
query {
  nodesEdges(
      workflows: ["*|*"],
      ids: ["*|baa"],
      states: ["submitted", "running", "failed", "waiting"],
      distance: 1) {
    nodes {
      id
      name
      cyclePoint
      parent: firstParent{ id state }
      state
      isHeld
    }
    edges {
      id
      source
      target
    }
  }
}
```
Results in most of your desired fields:
```
{
  "data": {
    "nodesEdges": {
      "nodes": [
        {
          "id": "sutherlander|noz|20190102T00|baa",
          "name": "baa",
          "cyclePoint": "20190102T00",
          "parent": {
            "id": "sutherlander|noz|20190102T00|FAM",
            "state": "waiting"
          },
          "state": "waiting",
          "isHeld": true
        },
        {
          "id": "sutherlander|noz|20190102T00|foo",
          "name": "foo",
          "cyclePoint": "20190102T00",
          "parent": {
            "id": "sutherlander|noz|20190102T00|root",
            "state": "waiting"
          },
          "state": "succeeded",
          "isHeld": true
        },
        {
          "id": "sutherlander|noz|20190102T00|bar",
          "name": "bar",
          "cyclePoint": "20190102T00",
          "parent": {
            "id": "sutherlander|noz|20190102T00|FAM",
            "state": "waiting"
          },
          "state": "",
          "isHeld": false
        }
      ],
      "edges": [
        {
          "id": "sutherlander|noz|foo.20190102T00|baa.20190102T00",
          "source": "sutherlander|noz|20190102T00|foo",
          "target": "sutherlander|noz|20190102T00|baa"
        },
        {
          "id": "sutherlander|noz|baa.20190102T00|bar.20190102T00",
          "source": "sutherlander|noz|20190102T00|baa",
          "target": "sutherlander|noz|20190102T00|bar"
        }
      ]
    }
  }
}
```
I'm not sure what you do with the `label` field, but perhaps this needs to be discussed first because I assume if might be a description of the dependency or a name.. i.e.
```
fragment tProxy on TaskProxy {
	prerequisites {
	  expression
    conditions{
      exprAlias
      reqState
    }
	   satisfied
  }
}
  
query {
  nodesEdges(
      workflows: ["*|*"],
      ids: ["*|baa"],
      states: ["submitted", "running", "failed", "waiting"],
      distance: 1) {
    nodes {
      id
      name
      cyclePoint
      parent: firstParent{ id state }
      state
      isHeld
    }
    edges {
      id
      source
      target
      label: targetNode{...tProxy}
      cond
      suicide
    }
  }
}
```
resulting in:
```
.
.
.
      "edges": [
        {
          "id": "sutherlander|noz|foo.20190102T00|baa.20190102T00",
          "source": "sutherlander|noz|20190102T00|foo",
          "target": "sutherlander|noz|20190102T00|baa",
          "label": {
            "prerequisites": [
              {
                "expression": "c0",
                "conditions": [
                  {
                    "exprAlias": "c0",
                    "reqState": "succeeded"
                  }
                ],
                "satisfied": true
              }
            ]
          },
          "cond": false,
          "suicide": false
        },
        {
          "id": "sutherlander|noz|baa.20190102T00|bar.20190102T00",
          "source": "sutherlander|noz|20190102T00|baa",
          "target": "sutherlander|noz|20190102T00|bar",
          "label": {
            "prerequisites": []
          },
          "cond": false,
          "suicide": false
        }
      ]
    }
  }
}
```
for now you could just us the edge id:
```
query {
  nodesEdges(
      workflows: ["*|*"],
      states: ["submitted", "running", "failed", "waiting"],
      distance: 1) {
    nodes {
      id
      name
      cyclePoint
      parent: firstParent{ id state }
      state
      isHeld
    }
    edges {
      id
      source
      target
      label: id
      cond
      suicide
    }
  }
}
```
Once we've settled on a `label` we could change the edges to include this field (and more information, probably move info from the task Prerequisites type)...

**Comment by dwsutherland** [comment]
Your code might have to handle non-existent nodes (that are specified on the edge), i.e. xtriggers... Otherwise I'll need to add an arg or default behaviour to only include edges with existing source/target.

**Comment by MartinRyan** [comment]
> Run-percent needs to be computed client-side, from start-time, current-time, and expected or average run-length. We discussed this somewhere recently, but offhand I can't recall exactly where. Basically it's a simple calculation that could be done at either end, but if server-side it would require constant frequent updates over the network which seem unnecessary.
> 
There are great performance problems with calculating this at the front end. Each time the layout is changed there would have to be a calculation for each each of thousands of running nodes, this will have a performance hit for the graph.
To create a calculation I would need the start time, expected or average run-length, or finish time, this would mean holding state somewhere in the front end and matching nodes for each graph layout and updating them. 
If runpercent can't be sent via graphql then hopefully start, meanRunTime and finish time can be provided. 
I still think this calculation should be done at the uiserver and sent as one property.
>
Hopefully changes to the radial progress bars on nodes representing running jobs can be updated every so often without redoing the graph layout. Initially it could just be done whenever the graph updates though.
>
any update to node styling requires a layout update

**Comment by MartinRyan** [comment]
> Your code might have to handle non-existent nodes (that are specified on the edge), i.e. xtriggers... Otherwise I'll need to add an arg or default behaviour to only include edges with existing source/target.

The graph can have nodes without edges, we would have to discuss exactly what xtriggers should look like, and what data property can be used to differentiate them.

**Comment by MartinRyan** [comment]
I can use the current time for calculations, but the ui doesn't have any knowledge of expected or average run time from previous runs, or the stop time, unless state is held for each node and then looked up for each node runpercent calculation. Each time the session is ended an average runtime would be lost.

**Comment by jarich** [comment]
>> Run-percent needs to be computed client-side, from start-time, current-time, and expected or average run-length.
> To create a calculation I would need the start time, expected or average run-length, or finish time...

Is it the intent that if a job is "stuck" (in some fashion such that it is seen as "running" for its entire expected/average run-length and more) that it will get to 99% complete and then wait at 99% until it becomes unstuck (through success or failure perhaps)?

I imagine that this request to @MartinRyan is to implement something akin to the following pseudo-code:

```
    # event: at every update count
    for every node:
        if node.completed is false and node.started is true:
            percentage_completed = ((now-start_time)/average_run_length) * 100
            if percentage_completed > 99:
                percentage_completed = 99
           node.update(percentage_complete = percentage_completed)
```

Note that the above has to be done for every node, even if there hasn't been any new information from the ui-server.
If the ui-server updates the average_run_length, is it okay if the percentage_completed value goes backwards?

Of course for families of tasks you may need to have a different algorithm to determine completeness.  That could be pretty tricky, given parallel tasks and the like, unless you are recording and providing average_run_length at the family level as well.

I second Martin's concerns about the cost of providing multiple concurrent progress bars, on-the-fly, in a web gui. Load moved off the server is load moved onto the user's browser, and given you don't know in advance the user's hardware (could it be a phone?), system load, or even whether the user is looking at it right now, combined with the inherent statelessness of HTML (even with the modern Javascript libraries) the performance challenges are non-zero.

How fast do you need these refresh times to be?
How fast do you need the initial page load to be?
Is it okay that if I open up the GUI in two different browsers that I might see slightly different values of completeness due to different update rates?

**Comment by hjoliver** [comment]
@MartinRyan and @jarich - more later when I have time, but a couple of quick points now.

There is a lot of unavoidable computation going on in the front-end already in the JS framework that we rely on and its interaction with the browser display engine. Worse, in the graph view, **graph layout** for big graphs, particularly hierarchical layouts such as we need, is **hugely expensive**.  We can do profiling to prove it (or not) of course, but I would be very very surprised if computing progress bars for a few nodes comes anywhere near to that as a concern.  

> any update to node styling requires a layout update

In principle that is not true - isn't that the essence of a data-driven reactive front-end?  We should only need to redo the layout if the set of graph nodes changes (i.e. lose some old nodes or gain some new ones).  Otherwise we ought to be able to (much more quickly) just change the style of some nodes, e.g. to reflect state changes, in the existing layout.  Whether Cytoscape puts some barrier in the way of that though, I don't know. (Of course we still have to worry about layout speed, because often the node set does change; our new n-distance window on the workflow will be best defense in large suites, if we can pull that off).

And by the way, progress bars are only needed for nodes with running jobs - which typically isn't a massive number at once even in massive workflows (although it could be of course - in which case see my point about lack of impact relative other computation that is not avoidable).

**Comment by hjoliver** [comment]
This front-end computation of progress is exactly the same as in the Cylc 7 GUI BTW. It only needs to be approximate, because we almost only have an approximate estimate of run-length anyway.

**Comment by hjoliver** [comment]
>  Each time the session is ended an average runtime would be lost.

We could compute average run time in the server (can't recall if we do or not in cylc-7) -  that does not change every second like a progress bar percentage does, so no additional/unwarranted network chatter.

**Comment by hjoliver** [comment]
@jarich - coming back to some of your specific questions...

> Is it the intent that if a job is "stuck" (in some fashion such that it is seen as "running" for its entire expected/average run-length and more) that it will get to 99% complete and then wait at 99% until it becomes unstuck (through success or failure perhaps)?

Generally yes - if a job gets "stuck" running longer than the computed average or the user-supplied estimated run length, then the progress bar will look more or less complete for all the extra time. And I don't think it matters if we choose 99% or 100%, particularly for a small radial progress bar.  That's probably the best we can do, and the user can easily infer that's what's going on: progress bar complete but job status still running means job taking longer than estimated. 

> If the ui-server updates the average_run_length, is it okay if the percentage_completed value goes backwards?

Yes, that's OK. Or at least it's a subjective judgement call (which option is least misleading?)

> Of course for families of tasks you may need to have a different algorithm to determine completeness. That could be pretty tricky, given parallel tasks and the like, unless you are recording and providing average_run_length at the family level as well.

We don't plan to have family (or cycle-point) completion progress, at least not as a continuous progress bar, essentially for the reasons you give. If there are any member tasks that have not started running yet then it's impossible to estimate completion because (in general) we can't know how long they might be delayed in internal or external queues etc. We are considering providng the integer fraction of member tasks that have completed, e.g. literally "4/10" or whatever.

> How fast do you need these refresh times to be?
> How fast do you need the initial page load to be?

As fast as possible, given what we need to display. But of course no matter what we do the real performance will be affected the size of the suites, and the capabilities/power of the software, hardware, and network that we depend on. 
  
> Is it okay that if I open up the GUI in two different browsers that I might see slightly different values of completeness due to different update rates?

It doesn't really matter (progress is just an estimate, again). But, if you see radically different values in different browsers then computing progress server-side is not going to help.

Fundamentally, progress is a trivial computation: `(now - start)/(approx_len)`. The server supplies `start` and `approx_len`, and they are (mostly) static.  The only variable is `now`, which a) changes continually, and b) the client knows it just as well as the server. So for long-running tasks it's a trade-off between trivial client-side computation vs continual unnecessary updates over the network.

**Comment by dwsutherland** [comment]
> Fundamentally, progress is a trivial computation: (now - start)/(approx_len). The server supplies start and approx_len, and they are (mostly) static. The only variable is now, which a) changes continually, and b) the client knows it just as well as the server. So for long-running tasks it's a trade-off between trivial client-side computation vs continual unnecessary updates over the network.

Yes, I would guess there's a heck of a lot more machinery in the communication of getting/receiving the end result from the UI Server than computing `(now - start)/(approx_len)` locally... and it's only done for running tasks (and potentially only for what's in view, if we head that)

**Comment by oliver-sanders** [comment]
Is this resolved?

**Comment by kinow** [comment]
I think so, but in the end I believe the changes were mainly in the graph view & component. There could be other changes that would be helpful for the graph, but I think we can create issues for those changes later, as required.

**Comment by hjoliver** [comment]
Yes, closing this.
